name: sync trakt data

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        working-directory: ./src
        run: |
          pip install -r requirements.txt

      - name: Sync data
        id: sync
        working-directory: ./src
        env:
          GH_BOT_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
          TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
          TRAKT_TOKEN: ${{ secrets.TRAKT_TOKEN }}
        run: |
          python sync_scrobble.py

      # 如果github output的TRAKT_TOKEN有更新，就更新到secrets.TRAKT_TOKEN
      - name: update TRAKT_TOKEN
        if: steps.sync.outputs.TRAKT_TOKEN != null
        uses: jon-grey/github-actions-secrets-creator@v1
        with:
          location: nichuanfang/trakt
          name: TRAKT_TOKEN
          value: ${{ steps.sync.outputs.TRAKT_TOKEN }}
          pa_token: ${{ secrets.GH_TOKEN }}
